In [1]:
import pandas as pd
df= pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
#convert 3 species into 0,1,2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df["Species"])

In [3]:
df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
54    55            6.5           2.8            4.6           1.5        1
2      3            4.7           3.2            1.3           0.2        0
83    84            6.0           2.7            5.1           1.6        1
64    65            5.6           2.9            3.6           1.3        1
88    89            5.6           3.0            4.1           1.3        1
24    25            4.8           3.4            1.9           0.2        0
5      6            5.4           3.9            1.7           0.4        0
127  128            6.1           3.0            4.9           1.8        2
95    96            5.7           3.0            4.2           1.2        1
55    56            5.7           2.8            4.5           1.3        1

In [4]:
from sklearn.model_selection import train_test_split
X= df.drop('Species', axis=1)
y= df['Species']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state= 42
)

In [14]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [16]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb= GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {'Logistic Regression': lr, 'Naive Bayes': nb, 'KNN': knn}

for name, model in models.items():
    y_pred= model.predict(X_test)
    print(f"\n{name}")

    print("Accuracy:", accuracy_score(y_test, y_pred))
    
    print("cm:", confusion_matrix(y_test, y_pred))

    print("classification report:", classification_report(y_test, y_pred))

Logistic Regression
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75


Naive Bayes
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75


KNN
Accuracy: 1.0
cm: [[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

In [18]:
from sklearn.model_selection import cross_val_score

for name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5)
    print(name, scores.mean())

Logistic Regression 0.8800000000000001
Naive Bayes 0.9933333333333334
KNN 0.8733333333333333